### ISSUE TITLE
amCharts and dynamic web objects

### ISSUE THREAD

**Issue by AlbinWisen** [stureaps/AmChartsComponent#5]
If used inside a cWebDynamicObjectContainer, OnClick events for charts throw a uncaught 999 error. Does not show to the user but you see it when debugging.

**Comment by jkruse** [comment]
Apparently DataFlex 2020 is more picky about parameter values of server calls, and does not accept for instance sending `null` to a string parameter. This version uses an empty string instead of `null` and should run with DataFlex 2020.

Note that there is also (now) a "dataflex-2020-preview" branch containing a workspace migrated to the 2020 alpha 2 preview, and in which I added a demo using cWebDynamicObjectContainer (so you can dynamically inject multiple charts).
